### ISSUE TITLE
Crash with open app

### ISSUE THREAD

**Issue by anirov** [Akylas/oss-weather#13]
Samsung, Android 8.0
`FATAL EXCEPTION: main
Process: com.akylas.weather, PID: 29227
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.akylas.weather/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreateView failed
Error: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/inspector/InspectionCompanion;
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: com.tns.NativeScriptException: Calling js method onCreateView failed
Error: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/inspector/InspectionCompanion;
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Unknown Source:118)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:102)
	at com.tns.Runtime.callJSMethod(Unknown Source:42)
	at com.tns.Runtime.callJSMethod(Unknown Source:7)
	at com.tns.Runtime.callJSMethod(Unknown Source:1)
	at com.tns.FragmentClass.onCreateView(Unknown Source:16)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:19)
	at androidx.fragment.app.w.f(:6)
	at androidx.fragment.app.w.k(:6)
	at androidx.fragment.app.FragmentManager.B(:9)
	at androidx.fragment.app.FragmentManager.T(Unknown Source:81)
	at androidx.fragment.app.FragmentManager.A(Unknown Source:30)
	at androidx.fragment.app.a.commitNowAllowingStateLoss(Unknown Source:6)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Unknown Source:118)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:102)
	at com.tns.Runtime.callJSMethod(Unknown Source:42)
	at com.tns.Runtime.callJSMethod(Unknown Source:7)
	at com.tns.Runtime.callJSMethod(Unknown Source:1)
	at com.tns.NativeScriptActivity.onStart(Unknown Source:7)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
	at android.app.Activity.performStart(Activity.java:7200)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/inspector/InspectionCompanion;
	... 33 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.inspector.InspectionCompanion" on path: DexPathList[[zip file "/data/app/com.akylas.weather-vAM9mE_l4PgJbEAZU3LpfA==/base.apk"],nativeLibraryDirectories=[/data/app/com.akylas.weather-vAM9mE_l4PgJbEAZU3LpfA==/lib/arm, /data/app/com.akylas.weather-vAM9mE_l4PgJbEAZU3LpfA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 33 more`

**Comment by farfromrefug** [comment]
@anirov thanks I ll fix it as soon as possible
