### ISSUE TITLE
Minor Chart Fixes

### ISSUE THREAD

**Issue by LinuxinaBit** [Akylas/oss-weather#265]
Some minor chart nitpicks:
1. Charts don't scroll as nicely as the standard bar graph in any view
2. The popup doesn't close when tapped unlike with the bar graph (it gets a bit annoying to navigate)
3. Icons can get a little bunched together at the end of a graph like this:

![Screenshot_20241210-185853-272](https://github.com/user-attachments/assets/620fe2d5-3f36-41d9-85e6-bb42b14fb64a)

**Comment by LinuxinaBit** [comment]
Scrolling a chart happens in steps and doesn’t keep going when release.
Here’s a video:

https://github.com/user-attachments/assets/b33cba8c-945c-4139-86df-d3c5f715d4cc

Thanks for looking into it :)

**Comment by Mrnofish** [comment]
Chart is currently causing a CTD, cannot access it at all:

```
FATAL EXCEPTION: main
Process: com.akylas.weather, PID: 24917
com.tns.NativeScriptException: Calling js method onDraw failed
Error: java.lang.Exception: Failed resolving method setColor on class android.graphics.Paint
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:1)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:100)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:3)
	at com.tns.gen.com.akylas.canvas.DrawListener.onDraw(Unknown Source:8)
	at com.akylas.canvas.CanvasView.dispatchDraw(Unknown Source:7)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4789)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4500)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3687)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.Exception: Failed resolving method setColor on class android.graphics.Paint
	at com.tns.Runtime.resolveMethodOverload(Unknown Source:97)
	... 83 more
```

**Comment by farfromrefug** [comment]
@LinuxinaBit yes there is no deceleration in the "chart" right Now. 
The other is a list. Not a big deal as the chart is "shorter" in content width. But I will try to look at it someday. No timeline though, especially since I wont be able to develop any new feature (just minor bi fixes) from march 2025 to september 2025.

**Comment by LinuxinaBit** [comment]
That's alright :)
Thank you!
