### ISSUE TITLE
[146] Tapping on any day triggers CTD 

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#266]
```
FATAL EXCEPTION: main
Process: com.akylas.weather, PID: 27242
com.tns.NativeScriptException: Calling js method onDraw failed
Error: java.lang.Exception: Failed resolving method setColor on class android.graphics.Paint
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:1)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:100)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:3)
	at com.tns.gen.com.akylas.canvas.DrawListener.onDraw(Unknown Source:8)
	at com.akylas.canvas.CanvasView.dispatchDraw(Unknown Source:7)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at androidx.core.widget.NestedScrollView.draw(SourceFile:1)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4789)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4500)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3687)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.Exception: Failed resolving method setColor on class android.graphics.Paint
	at com.tns.Runtime.resolveMethodOverload(Unknown Source:97)
	... 82 more
```

**Comment by cb8121** [comment]
@Mrnofish do you have the option "show hourly chart on daily view" activated? 
I experienced the same issue. If the option "show hourly chart on main view" is active you would even get a crash on startup.

**Comment by Mrnofish** [comment]
Yeah, "Hourly chart on daily view" is enabled.

Not getting any crashes on start-up with it on, though, only when I tap on a day.

But enabling "Hourly chart on main view" does make the roof come down crashing pretty hard.

**Comment by farfromrefug** [comment]
@Mrnofish managed to reproduce it. sorry about that

**Comment by 0-5-0** [comment]
This should be fixed in the latest version (147), at least it works for me with the new version that got released.

**Comment by Mrnofish** [comment]
Yup, it seems okay now. Closing!
